CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_public_id UNIQUE (public_id),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));

CREATE TABLE merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    name VARCHAR(200) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_merchants PRIMARY KEY (id),
    CONSTRAINT uq_merchants_public_id UNIQUE (public_id),
    CONSTRAINT ck_merchants_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
);

CREATE TABLE merchant_members (
    merchant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_merchant_members PRIMARY KEY (merchant_id, user_id),
    CONSTRAINT fk_merchant_members_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT fk_merchant_members_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_merchant_members_role
        CHECK (role IN ('OWNER', 'ADMIN', 'DEVELOPER', 'FINANCE', 'VIEWER'))
);

CREATE INDEX ix_merchant_members_user ON merchant_members (user_id);
