CREATE TABLE merchant_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    merchant_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    key_prefix VARCHAR(64) NOT NULL,
    key_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_used_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    revoked_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_merchant_api_keys PRIMARY KEY (id),
    CONSTRAINT uq_merchant_api_keys_public_id UNIQUE (public_id),
    CONSTRAINT uq_merchant_api_keys_key_prefix UNIQUE (key_prefix),
    CONSTRAINT fk_merchant_api_keys_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT ck_merchant_api_keys_status CHECK (status IN ('ACTIVE', 'REVOKED'))
);

CREATE INDEX ix_merchant_api_keys_merchant_status
    ON merchant_api_keys (merchant_id, status);
