CREATE TABLE payment_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    merchant_id BIGINT NOT NULL,
    merchant_order_id VARCHAR NULL,
    description VARCHAR NULL,
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR NOT NULL,
    refunded_amount_minor BIGINT NOT NULL DEFAULT 0,
    refund_reserved_minor BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_payment_intents PRIMARY KEY (id),
    CONSTRAINT uq_payment_intents_public_id UNIQUE (public_id),
    CONSTRAINT fk_payment_intents_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT ck_payment_intents_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT ck_payment_intents_refund_amounts CHECK (
        refunded_amount_minor >= 0
        AND refund_reserved_minor >= 0
        AND refunded_amount_minor + refund_reserved_minor <= amount_minor
    ),
    CONSTRAINT ck_payment_intents_status CHECK (
        status IN ('CREATED', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'PARTIALLY_REFUNDED', 'REFUNDED')
    )
);

CREATE INDEX ix_payment_intents_merchant_created_at
    ON payment_intents (merchant_id, created_at DESC);

CREATE INDEX ix_payment_intents_merchant_status_created_at
    ON payment_intents (merchant_id, status, created_at DESC);

CREATE INDEX ix_payment_intents_merchant_order_id
    ON payment_intents (merchant_id, merchant_order_id);

CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    payment_intent_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    provider VARCHAR NOT NULL,
    provider_transaction_id VARCHAR NULL,
    status VARCHAR NOT NULL,
    failure_code VARCHAR NULL,
    failure_message VARCHAR NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_payment_transactions PRIMARY KEY (id),
    CONSTRAINT uq_payment_transactions_public_id UNIQUE (public_id),
    CONSTRAINT uq_payment_transactions_intent_attempt UNIQUE (payment_intent_id, attempt_no),
    CONSTRAINT fk_payment_transactions_payment_intent
        FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id),
    CONSTRAINT ck_payment_transactions_attempt_positive CHECK (attempt_no > 0),
    CONSTRAINT ck_payment_transactions_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'UNKNOWN')
    )
);
