CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id BIGINT NOT NULL,
    operation VARCHAR NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    status VARCHAR NOT NULL,
    resource_type VARCHAR NULL,
    resource_public_id VARCHAR NULL,
    http_status INTEGER NULL,
    response_payload JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_idempotency_records PRIMARY KEY (id),
    CONSTRAINT fk_idempotency_records_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT uq_idempotency_records_scope
        UNIQUE (merchant_id, operation, idempotency_key),
    CONSTRAINT ck_idempotency_records_operation CHECK (
        operation IN ('PAYMENT_INTENT_CREATE', 'PAYMENT_INTENT_CONFIRM')
    ),
    CONSTRAINT ck_idempotency_records_request_hash CHECK (
        request_hash ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_idempotency_records_status CHECK (
        status IN ('PROCESSING', 'COMPLETED', 'FAILED')
    )
);

CREATE INDEX ix_idempotency_records_status_expires_at
    ON idempotency_records (status, expires_at);
