CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    merchant_id BIGINT NOT NULL,
    payment_intent_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR NOT NULL,
    reason VARCHAR(255) NULL,
    provider VARCHAR NOT NULL,
    provider_refund_id VARCHAR NULL,
    failure_code VARCHAR NULL,
    failure_message VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_refunds PRIMARY KEY (id),
    CONSTRAINT uq_refunds_public_id UNIQUE (public_id),
    CONSTRAINT fk_refunds_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT fk_refunds_payment_intent
        FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id),
    CONSTRAINT ck_refunds_amount_positive CHECK (amount_minor > 0)
);

CREATE INDEX ix_refunds_payment_intent_created_at
    ON refunds (payment_intent_id, created_at DESC);

CREATE INDEX ix_refunds_merchant_created_at
    ON refunds (merchant_id, created_at DESC);

CREATE INDEX ix_refunds_merchant_status_created_at
    ON refunds (merchant_id, status, created_at DESC);

ALTER TABLE idempotency_records
    DROP CONSTRAINT ck_idempotency_records_operation;

ALTER TABLE idempotency_records
    ADD CONSTRAINT ck_idempotency_records_operation CHECK (
        operation IN (
            'PAYMENT_INTENT_CREATE',
            'PAYMENT_INTENT_CONFIRM',
            'REFUND_CREATE'
        )
    );
