CREATE TABLE ledger_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    account_code VARCHAR NOT NULL,
    account_type VARCHAR NOT NULL,
    owner_type VARCHAR NOT NULL,
    owner_id BIGINT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_ledger_accounts PRIMARY KEY (id),
    CONSTRAINT uq_ledger_accounts_public_id UNIQUE (public_id),
    CONSTRAINT uq_ledger_accounts_account_code UNIQUE (account_code),
    CONSTRAINT ck_ledger_accounts_type CHECK (
        account_type IN ('SYSTEM_CLEARING', 'MERCHANT_PAYABLE')
    ),
    CONSTRAINT ck_ledger_accounts_owner_type CHECK (
        owner_type IN ('SYSTEM', 'MERCHANT')
    ),
    CONSTRAINT ck_ledger_accounts_status CHECK (
        status IN ('ACTIVE', 'CLOSED')
    ),
    CONSTRAINT ck_ledger_accounts_owner CHECK (
        (
            account_type = 'SYSTEM_CLEARING'
            AND owner_type = 'SYSTEM'
            AND owner_id IS NULL
        )
        OR
        (
            account_type = 'MERCHANT_PAYABLE'
            AND owner_type = 'MERCHANT'
            AND owner_id IS NOT NULL
            AND owner_id > 0
        )
    )
);

CREATE TABLE ledger_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    posting_type VARCHAR NOT NULL,
    reference_type VARCHAR NOT NULL,
    reference_id VARCHAR NOT NULL,
    currency CHAR(3) NOT NULL,
    description VARCHAR NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_ledger_transactions PRIMARY KEY (id),
    CONSTRAINT uq_ledger_transactions_public_id UNIQUE (public_id),
    CONSTRAINT uq_ledger_transactions_business_reference UNIQUE (
        posting_type,
        reference_type,
        reference_id
    ),
    CONSTRAINT ck_ledger_transactions_posting_type CHECK (
        posting_type IN ('PAYMENT_SUCCEEDED', 'REFUND_SUCCEEDED', 'REVERSAL')
    ),
    CONSTRAINT ck_ledger_transactions_reference_type CHECK (
        reference_type IN ('PAYMENT_INTENT', 'REFUND', 'LEDGER_TRANSACTION')
    ),
    CONSTRAINT ck_ledger_transactions_reference CHECK (
        (posting_type = 'PAYMENT_SUCCEEDED' AND reference_type = 'PAYMENT_INTENT')
        OR (posting_type = 'REFUND_SUCCEEDED' AND reference_type = 'REFUND')
        OR (posting_type = 'REVERSAL' AND reference_type = 'LEDGER_TRANSACTION')
    )
);

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ledger_transaction_id BIGINT NOT NULL,
    ledger_account_id BIGINT NOT NULL,
    entry_no INTEGER NOT NULL,
    direction VARCHAR NOT NULL,
    amount_minor BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_ledger_entries PRIMARY KEY (id),
    CONSTRAINT fk_ledger_entries_transaction
        FOREIGN KEY (ledger_transaction_id) REFERENCES ledger_transactions (id),
    CONSTRAINT fk_ledger_entries_account
        FOREIGN KEY (ledger_account_id) REFERENCES ledger_accounts (id),
    CONSTRAINT uq_ledger_entries_transaction_entry_no UNIQUE (
        ledger_transaction_id,
        entry_no
    ),
    CONSTRAINT ck_ledger_entries_entry_no_positive CHECK (entry_no > 0),
    CONSTRAINT ck_ledger_entries_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_ledger_entries_amount_positive CHECK (amount_minor > 0)
);
