CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR NOT NULL,
    aggregate_type VARCHAR NOT NULL,
    aggregate_id VARCHAR NOT NULL,
    event_type VARCHAR NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    available_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_outbox_events PRIMARY KEY (id),
    CONSTRAINT uq_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_outbox_events_status CHECK (
        status IN ('PENDING', 'PUBLISHED', 'FAILED')
    ),
    CONSTRAINT ck_outbox_events_retry_count CHECK (retry_count >= 0),
    CONSTRAINT ck_outbox_events_publication_state CHECK (
        (status = 'PUBLISHED' AND published_at IS NOT NULL)
        OR
        (status IN ('PENDING', 'FAILED') AND published_at IS NULL)
    )
);

CREATE INDEX ix_outbox_events_status_available_at
    ON outbox_events (status, available_at);
