CREATE TABLE webhook_endpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    merchant_id BIGINT NOT NULL,
    url VARCHAR(2048) NOT NULL,
    secret_ciphertext TEXT NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_webhook_endpoints PRIMARY KEY (id),
    CONSTRAINT uq_webhook_endpoints_public_id UNIQUE (public_id),
    CONSTRAINT fk_webhook_endpoints_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT ck_webhook_endpoints_status CHECK (
        status IN ('ACTIVE', 'DISABLED')
    )
);

CREATE INDEX ix_webhook_endpoints_merchant_status_created_at
    ON webhook_endpoints (merchant_id, status, created_at DESC);

CREATE TABLE webhook_endpoint_events (
    endpoint_id BIGINT NOT NULL,
    event_type VARCHAR NOT NULL,
    CONSTRAINT pk_webhook_endpoint_events PRIMARY KEY (endpoint_id, event_type),
    CONSTRAINT fk_webhook_endpoint_events_endpoint
        FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoints (id),
    CONSTRAINT ck_webhook_endpoint_events_event_type CHECK (
        event_type IN (
            'payment.processing',
            'payment.succeeded',
            'payment.failed',
            'refund.processing',
            'refund.succeeded',
            'refund.failed'
        )
    )
);
