CREATE TABLE webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    source_event_id VARCHAR NOT NULL,
    merchant_id BIGINT NOT NULL,
    event_type VARCHAR NOT NULL,
    resource_type VARCHAR NOT NULL,
    resource_id VARCHAR NOT NULL,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_webhook_events PRIMARY KEY (id),
    CONSTRAINT uq_webhook_events_public_id UNIQUE (public_id),
    CONSTRAINT uq_webhook_events_source_event_id UNIQUE (source_event_id),
    CONSTRAINT fk_webhook_events_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT ck_webhook_events_event_type CHECK (
        event_type IN (
            'payment.processing', 'payment.succeeded', 'payment.failed',
            'refund.processing', 'refund.succeeded', 'refund.failed'
        )
    ),
    CONSTRAINT ck_webhook_events_resource_type CHECK (
        resource_type IN ('PAYMENT_INTENT', 'REFUND')
    )
);

CREATE TABLE webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR NOT NULL,
    webhook_event_id BIGINT NOT NULL,
    webhook_endpoint_id BIGINT NOT NULL,
    status VARCHAR NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NULL,
    lease_expires_at TIMESTAMPTZ NULL,
    delivered_at TIMESTAMPTZ NULL,
    last_http_status INTEGER NULL,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_webhook_deliveries PRIMARY KEY (id),
    CONSTRAINT uq_webhook_deliveries_public_id UNIQUE (public_id),
    CONSTRAINT uq_webhook_deliveries_event_endpoint UNIQUE (webhook_event_id, webhook_endpoint_id),
    CONSTRAINT fk_webhook_deliveries_event
        FOREIGN KEY (webhook_event_id) REFERENCES webhook_events (id),
    CONSTRAINT fk_webhook_deliveries_endpoint
        FOREIGN KEY (webhook_endpoint_id) REFERENCES webhook_endpoints (id),
    CONSTRAINT ck_webhook_deliveries_status CHECK (
        status IN ('PENDING', 'DELIVERING', 'DELIVERED', 'RETRYING', 'DEAD')
    ),
    CONSTRAINT ck_webhook_deliveries_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_webhook_deliveries_last_http_status CHECK (
        last_http_status IS NULL OR last_http_status BETWEEN 100 AND 599
    ),
    CONSTRAINT ck_webhook_deliveries_state_timestamps CHECK (
        (status IN ('PENDING', 'RETRYING')
            AND next_attempt_at IS NOT NULL AND lease_expires_at IS NULL AND delivered_at IS NULL)
        OR
        (status = 'DELIVERING'
            AND next_attempt_at IS NULL AND lease_expires_at IS NOT NULL AND delivered_at IS NULL)
        OR
        (status = 'DELIVERED'
            AND next_attempt_at IS NULL AND lease_expires_at IS NULL AND delivered_at IS NOT NULL)
        OR
        (status = 'DEAD'
            AND next_attempt_at IS NULL AND lease_expires_at IS NULL AND delivered_at IS NULL)
    )
);

CREATE INDEX ix_webhook_deliveries_status_next_attempt_at
    ON webhook_deliveries (status, next_attempt_at);

CREATE INDEX ix_webhook_deliveries_status_lease_expires_at
    ON webhook_deliveries (status, lease_expires_at);

CREATE INDEX ix_webhook_deliveries_endpoint_created_at
    ON webhook_deliveries (webhook_endpoint_id, created_at DESC);

CREATE TABLE webhook_delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    delivery_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NULL,
    http_status INTEGER NULL,
    duration_ms INTEGER NULL,
    error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_webhook_delivery_attempts PRIMARY KEY (id),
    CONSTRAINT uq_webhook_delivery_attempts_delivery_attempt_no UNIQUE (delivery_id, attempt_no),
    CONSTRAINT fk_webhook_delivery_attempts_delivery
        FOREIGN KEY (delivery_id) REFERENCES webhook_deliveries (id),
    CONSTRAINT ck_webhook_delivery_attempts_attempt_no CHECK (attempt_no > 0),
    CONSTRAINT ck_webhook_delivery_attempts_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_webhook_delivery_attempts_http_status CHECK (
        http_status IS NULL OR http_status BETWEEN 100 AND 599
    )
);
